# =============================================================================
# Harness Chaos Engineering — Kubernetes Onboarding
# Generated by harness-chaos-advisor-agent
# =============================================================================

locals {
  tags_set = [for k, v in var.tags : "${k}=${v}"]
}

# -----------------------------------------------------------------------------
# 1. Organization
# -----------------------------------------------------------------------------
resource "harness_platform_organization" "chaos_org" {
  identifier  = var.org_identifier
  name        = var.org_name
  description = "Organization for Chaos Engineering onboarding"
  tags        = local.tags_set
}

# -----------------------------------------------------------------------------
# 2. Project
# -----------------------------------------------------------------------------
resource "harness_platform_project" "chaos_project" {
  depends_on = [harness_platform_organization.chaos_org]

  identifier  = var.project_identifier
  name        = var.project_name
  org_id      = harness_platform_organization.chaos_org.id
  description = "Project for Kubernetes chaos engineering"
  tags        = local.tags_set
}

# -----------------------------------------------------------------------------
# 3. Kubernetes Connector (delegate assume-role method)
# -----------------------------------------------------------------------------
resource "harness_platform_connector_kubernetes" "chaos_k8s" {
  depends_on = [harness_platform_project.chaos_project]

  identifier = var.k8s_connector_identifier
  name       = var.k8s_connector_name
  org_id     = harness_platform_organization.chaos_org.id
  project_id = harness_platform_project.chaos_project.id

  inherit_from_delegate {
    delegate_selectors = var.delegate_selectors
  }

  description = "Kubernetes connector for chaos engineering (inherits credentials from delegate)"
  tags        = local.tags_set
}

# -----------------------------------------------------------------------------
# Outputs
# -----------------------------------------------------------------------------
output "organization_id" {
  description = "Created organization identifier"
  value       = harness_platform_organization.chaos_org.id
}

output "project_id" {
  description = "Created project identifier"
  value       = harness_platform_project.chaos_project.id
}

output "k8s_connector_id" {
  description = "Kubernetes connector identifier"
  value       = harness_platform_connector_kubernetes.chaos_k8s.id
}
